# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(numpy.__version__)
print(numpy.show_config())

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
z = numpy.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
z = numpy.zeros((10, 10))
print(z)
print(z.size)
print(z.itemsize)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
100
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
z = numpy.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
z = numpy.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
z = numpy.arange(10, 50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
z = numpy.arange(0, 9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
nz = numpy.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
z = numpy.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
z = numpy.random.random((3, 3, 3))
print(z)

[[[0.74262812 0.93211084 0.0597122 ]
  [0.88403872 0.03061072 0.34015044]
  [0.3428864  0.61334623 0.76709853]]

 [[0.3482669  0.92198728 0.96004986]
  [0.40519648 0.0959276  0.42684398]
  [0.00447487 0.6921436  0.01834241]]

 [[0.04343323 0.01213703 0.02749045]
  [0.77490229 0.44443809 0.29384426]
  [0.31826732 0.89503988 0.15033402]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
z = numpy.random.random((10, 10))
print(z)
z_min, z_max = z.min(), z.max()
print(z_min, z_max)

[[0.98326683 0.81337098 0.81372898 0.18519475 0.04497973 0.63272871
  0.17256644 0.31262966 0.07506322 0.40512606]
 [0.92791699 0.88116771 0.46803165 0.22318651 0.89743344 0.24294687
  0.58265379 0.02103056 0.36220969 0.47666626]
 [0.03071131 0.62502677 0.72490816 0.18134793 0.47246506 0.13029187
  0.92447836 0.55620751 0.28600853 0.11229215]
 [0.15205673 0.84953293 0.70533859 0.61231853 0.75639276 0.31490702
  0.13437895 0.90701135 0.8180866  0.0545151 ]
 [0.34555836 0.39281645 0.10133725 0.20293148 0.13495743 0.36973774
  0.3531171  0.79513286 0.63672142 0.37733562]
 [0.61192644 0.03764845 0.19323441 0.3974209  0.45737164 0.00325705
  0.98092876 0.46087441 0.26840432 0.89444886]
 [0.63934758 0.07692071 0.84780146 0.22930508 0.61099949 0.42456669
  0.89771097 0.74611135 0.20947897 0.15887365]
 [0.52249583 0.6173337  0.30293318 0.1343499  0.18742859 0.94082952
  0.56700564 0.57497886 0.05971033 0.65350793]
 [0.68425482 0.19687517 0.61219815 0.39631703 0.17378857 0.63314473
  0.31975646

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
z = numpy.random.random(30)
print(z)
z_mean = z.mean()
print(z_mean)

[0.30069808 0.32410655 0.51861476 0.80001382 0.90788521 0.06703837
 0.9489159  0.31706806 0.6463055  0.17135082 0.24090388 0.15016216
 0.94298196 0.12286521 0.55599972 0.0813035  0.06255298 0.22133225
 0.60943606 0.56485676 0.24158584 0.38048571 0.11418934 0.27092045
 0.56832836 0.17576538 0.14046294 0.46399582 0.89842347 0.15934177]
0.3989296882942066


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
z = numpy.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [25]:
z = numpy.ones((5, 5))
z = numpy.pad(z, pad_width = 1, mode = 'constant', constant_values = 0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
print(0 * numpy.nan)
print(numpy.nan == numpy.nan)
print(numpy.inf, numpy.inf > numpy.nan, numpy.inf < numpy.nan)
print(numpy.nan - numpy.nan)
print(numpy.nan in set([numpy.nan]))
print(0.3 == 3 * 0.1, 0.3, 3 * 0.1)

nan
False
inf False False
nan
True
False 0.3 0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
z = numpy.diag(numpy.arange(4) + 1, k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
z = numpy.zeros((8, 8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
print(numpy.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
z = numpy.tile(numpy.array([[0, 1], [1, 0]]), [4, 4])
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
z = numpy.random.random((5, 5))
print(z)
print(numpy.mean(z))
print(numpy.std(z))
z = (z - numpy.mean(z)) / numpy.std(z)
print(z)

[[0.7622236  0.85457512 0.93598941 0.51465243 0.32196108]
 [0.02647121 0.91112328 0.44953349 0.80810668 0.01670383]
 [0.6541528  0.39475649 0.59648682 0.40378794 0.09617561]
 [0.48136891 0.10075541 0.20731369 0.56621149 0.8114967 ]
 [0.47700908 0.68298148 0.07256985 0.44802973 0.22118189]]
0.47262472057378857
0.28160277037963166
[[ 1.02839499  1.35634461  1.64545501  0.14924465 -0.53502188]
 [-1.58433637  1.55715286 -0.08199929  1.19133046 -1.61902132]
 [ 0.64462461 -0.276518    0.43984689 -0.24444638 -1.33680897]
 [ 0.03105149 -1.32054564 -0.94214637  0.33233611  1.20336876]
 [ 0.0155693   0.7469982  -1.42063542 -0.08733929 -0.89289901]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [40]:
color = numpy.dtype([('r', numpy.ubyte, 0), ('g', numpy.ubyte, 0), ('b', numpy.ubyte, 0), ('a', numpy.ubyte, 0)])
print(color)

[('r', 'u1', (0,)), ('g', 'u1', (0,)), ('b', 'u1', (0,)), ('a', 'u1', (0,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [42]:
z1 = numpy.random.random((5, 3))
z2 = numpy.random.random((3, 2))
z = numpy.dot(z1, z2)
print(z1)
print(z2)
print(z)

[[0.19631427 0.13981999 0.38991141]
 [0.17131638 0.63400303 0.00581813]
 [0.00896955 0.37135948 0.14422279]
 [0.82185658 0.94167208 0.87287349]
 [0.05306975 0.5728044  0.11732765]]
[[0.4855777  0.38371423]
 [0.41778229 0.70400854]
 [0.26087373 0.93612457]]
[[0.25545779 0.5387687 ]
 [0.34958045 0.51752658]
 [0.19712676 0.39989249]
 [1.02019891 1.79542158]
 [0.29568472 0.5334561 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [44]:
z = numpy.arange(10)
print(z)
z[(z > 3) & (z < 8)] *= -1
print(z)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
z = numpy.arange(10)
print(z)
print('z ** z', z ** z)
print('2 << z >> 2', 2 << z >> 2) # 先将2左移z位，再将结果右移2位
print('z <- z', z <- z) # z <- z 相当于 z < -z
print('1j * z', 1j * z)
print('z / 1 / 1', z / 1 / 1)

[0 1 2 3 4 5 6 7 8 9]
z ** z [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
2 << z >> 2 [  0   1   2   4   8  16  32  64 128 256]
z <- z [False False False False False False False False False False]
1j * z [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
z / 1 / 1 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [52]:
print(numpy.array(0) / numpy.array(0))
print(numpy.array(0) // numpy.array(0))
print(numpy.array([numpy.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/baiye/anaconda3/envs/Python 3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/baiye/anaconda3/envs/Python 3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [53]:
z = numpy.random.uniform(-10, 10, 10)
print(z)
z = numpy.copysign(numpy.ceil(numpy.abs(z)), z)
print(z)

[ 4.62235195  4.89565021  5.67731575  7.08527435  0.45902763 -2.11276991
  8.5705684  -4.89224819 -1.41095253 -2.3128234 ]
[ 5.  5.  6.  8.  1. -3.  9. -5. -2. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [54]:
z1 = numpy.random.randint(0, 10, 10)
z2 = numpy.random.randint(0, 10, 10)
z = numpy.intersect1d(z1, z2)
print(z1)
print(z2)
print(z)

[0 4 6 3 7 9 4 7 2 0]
[2 0 8 2 9 3 3 4 5 0]
[0 2 3 4 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [55]:
defaults = numpy.seterr(all='ignore')
print(defaults)

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
print(numpy.sqrt(-1))
print(numpy.emath.sqrt(-1))
print(numpy.sqrt(-1) == numpy.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [58]:
yesterday = numpy.datetime64('today', 'D') - numpy.timedelta64(1, 'D')
today = numpy.datetime64('today', 'D')
tomorrow = numpy.datetime64('today', 'D') + numpy.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-04-08
2019-04-09
2019-04-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [60]:
z = numpy.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [61]:
A = numpy.ones(3) * 1
B = numpy.ones(3) * 2
print(A)
print(B)
numpy.add(A, B, out = B)
numpy.divide(A, 2, out = A)
numpy.negative(A, out = A)
numpy.multiply(A, B, out = A)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [63]:
z = numpy.random.uniform(0, 10, 10)
print(z)

print(z - z % 1)
print(numpy.floor(z))
print(numpy.ceil(z) - 1)
print(z.astype(int))
print(numpy.trunc(z))

[7.20818761 8.3820005  9.13879509 6.84265397 9.06376422 3.39631437
 5.79562208 6.41618463 7.31297882 9.11846864]
[7. 8. 9. 6. 9. 3. 5. 6. 7. 9.]
[7. 8. 9. 6. 9. 3. 5. 6. 7. 9.]
[7. 8. 9. 6. 9. 3. 5. 6. 7. 9.]
[7 8 9 6 9 3 5 6 7 9]
[7. 8. 9. 6. 9. 3. 5. 6. 7. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
z = numpy.zeros((5, 5))
print(z)
z += numpy.arange(5)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [65]:
def generate():
    for i in range(10):
        yield i

z = numpy.fromiter(generate(), dtype = float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [67]:
z = numpy.linspace(0, 1, 11, endpoint = False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [2]:
z = numpy.random.random(10)
print(z)
z.sort()
print(z)

[0.34251395 0.63179198 0.86212178 0.50182918 0.89779259 0.04615237
 0.23816976 0.31623179 0.24415288 0.94070911]
[0.04615237 0.23816976 0.24415288 0.31623179 0.34251395 0.50182918
 0.63179198 0.86212178 0.89779259 0.94070911]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [3]:
z = numpy.arange(10)
print(numpy.add.reduce(z))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [5]:
a = numpy.random.randint(0, 2, 5)
b = numpy.random.randint(0, 2, 5)
print(a)
print(b)

equal = numpy.allclose(a, b)
print(equal)

equal = numpy.array_equal(a, b)
print(equal)

[1 0 1 0 0]
[0 1 0 0 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [6]:
z = numpy.zeros(10)
print(z)
z.flags.writeable = False
z[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [11]:
z = numpy.random.random((10, 2))
print(z)
x, y = z[:, 0], z[:, 1]
print(x)
print(y)
r = numpy.sqrt(x ** 2 + y ** 2)
t = numpy.arctan2(y, x)
print(r)
print(t)

[[0.41827219 0.64715557]
 [0.08183184 0.5058084 ]
 [0.99742799 0.60302257]
 [0.20270847 0.23569447]
 [0.19559692 0.61924829]
 [0.41306685 0.6894812 ]
 [0.40932374 0.46564851]
 [0.28099751 0.1811595 ]
 [0.1309106  0.31561209]
 [0.57128081 0.05903103]]
[0.41827219 0.08183184 0.99742799 0.20270847 0.19559692 0.41306685
 0.40932374 0.28099751 0.1309106  0.57128081]
[0.64715557 0.5058084  0.60302257 0.23569447 0.61924829 0.6894812
 0.46564851 0.1811595  0.31561209 0.05903103]
[0.7705595  0.51238519 1.16554658 0.31087394 0.6494048  0.80374657
 0.6199794  0.33433272 0.34168491 0.57432258]
[0.99700962 1.41040182 0.54377855 0.86049794 1.26485163 1.03104028
 0.84968267 0.57264137 1.17761111 0.10296559]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [12]:
z = numpy.random.random(10)
print(z)
z[z.argmax()] = 0
print(z)

[0.41079956 0.00458718 0.4625698  0.56137525 0.07803762 0.23670523
 0.19324625 0.74244531 0.28902565 0.270576  ]
[0.41079956 0.00458718 0.4625698  0.56137525 0.07803762 0.23670523
 0.19324625 0.         0.28902565 0.270576  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [14]:
z = numpy.zeros((5, 5), [('x', float), ('y', float)])
print(z)
z['x'], z['y'] = numpy.meshgrid(numpy.linspace(0, 1, 5), numpy.linspace(0, 1, 5))
print(z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [15]:
x = numpy.arange(10)
y = x + 0.5
c = 1.0 / numpy.subtract.outer(x, y)
print(numpy.linalg.det(c))

33961.93294480236


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [16]:
for dtype in [numpy.int8, numpy.int32, numpy.int64]:
    print(numpy.iinfo(dtype).min)
    print(numpy.iinfo(dtype).max)
for dtype in [numpy.float32, numpy.float64]:
    print(numpy.finfo(dtype).min)
    print(numpy.finfo(dtype).max)
    print(numpy.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [20]:
x = numpy.arange(100)
y = numpy.random.uniform(0, 100)
print(x)
print(y)
z = numpy.abs(x - y)
print(z)
print(z.argmin())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
4.6374201995372015
[ 4.6374202  3.6374202  2.6374202  1.6374202  0.6374202  0.3625798
  1.3625798  2.3625798  3.3625798  4.3625798  5.3625798  6.3625798
  7.3625798  8.3625798  9.3625798 10.3625798 11.3625798 12.3625798
 13.3625798 14.3625798 15.3625798 16.3625798 17.3625798 18.3625798
 19.3625798 20.3625798 21.3625798 22.3625798 23.3625798 24.3625798
 25.3625798 26.3625798 27.3625798 28.3625798 29.3625798 30.3625798
 31.3625798 32.3625798 33.3625798 34.3625798 35.3625798 36.3625798
 37.3625798 38.3625798 39.3625798 40.3625798 41.3625798 42.3625798
 43.3625798 44.3625798 45.3625798 46.3625798 47.3625798 48.3625798
 49.3625798 50.3625798 51.3625798 52.3625798 53.3625798 54.3625798
 55.3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [22]:
dtype = [('position', [('x', float, 0), ('y', float, 0)]),
            ('color', [('r', float, 0), ('g', float, 0), ('b', float, 0)])]
z = numpy.zeros(10, dtype=dtype)
print(z)

[(([], []), ([], [], [])) (([], []), ([], [], []))
 (([], []), ([], [], [])) (([], []), ([], [], []))
 (([], []), ([], [], [])) (([], []), ([], [], []))
 (([], []), ([], [], [])) (([], []), ([], [], []))
 (([], []), ([], [], [])) (([], []), ([], [], []))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [24]:
z = numpy.random.random((10, 2))
print(z)
x, y = numpy.atleast_2d(z[:, 0], z[:, 1])
print(x)
print(y)
d = numpy.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(d)

[[0.34278912 0.07357136]
 [0.3932748  0.86056552]
 [0.90421643 0.15337654]
 [0.96469076 0.16219344]
 [0.21538268 0.1700594 ]
 [0.83081805 0.65773924]
 [0.6852194  0.75235755]
 [0.08480669 0.47019542]
 [0.38956351 0.91001674]
 [0.01194584 0.42577155]]
[[0.34278912 0.3932748  0.90421643 0.96469076 0.21538268 0.83081805
  0.6852194  0.08480669 0.38956351 0.01194584]]
[[0.07357136 0.86056552 0.15337654 0.16219344 0.1700594  0.65773924
  0.75235755 0.47019542 0.91001674 0.42577155]]
[[0.         0.78861183 0.56707097 0.6281843  0.15981972 0.76119928
  0.76026915 0.47314436 0.83775219 0.48322071]
 [0.78861183 0.         0.87245493 0.90235235 0.71305281 0.48226818
  0.31135289 0.49753531 0.04959029 0.57832307]
 [0.56707097 0.87245493 0.         0.06111368 0.68903574 0.50967544
  0.6377601  0.8785252  0.91508033 0.93292328]
 [0.6281843  0.90235235 0.06111368 0.         0.74934936 0.51331037
  0.65299151 0.93223451 0.94340396 0.9885324 ]
 [0.15981972 0.71305281 0.68903574 0.74934936 0.         

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [27]:
z = numpy.arange(10, dtype=numpy.float32)
print(z)
z = z.astype(numpy.int32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [28]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n6, , , 7, 8\n, , 9, 10, 11""")
z = numpy.genfromtxt(s, delimiter=',', dtype=numpy.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [31]:
z = numpy.arange(9).reshape(3, 3)
print(z)
for index, value in numpy.ndenumerate(z):
    print(index, value)
for index in numpy.ndindex(z.shape):
    print(index, z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [33]:
x, y = numpy.meshgrid(numpy.linspace(-1, 1, 10), numpy.linspace(-1, 1, 10))
print(x)
print(y)
d = numpy.sqrt(x * x + y * y)
print(d)
sigma, mu = 1.0, 0.0
g = numpy.exp(-((d - mu)**2 / (2.0 * sigma ** 2)))
print(g)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [34]:
n = 10
p = 3
z = numpy.zeros((n, n))
print(z)
numpy.put(z, numpy.random.choice(range(n * n), p, replace=False), 1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [36]:
x = numpy.random.rand(5, 10)
print(x)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[0.41251014 0.23270817 0.15722318 0.73161816 0.24777524 0.33344057
  0.13429523 0.25844061 0.45079419 0.71900558]
 [0.0746453  0.76897165 0.80284911 0.89465068 0.88574415 0.03283538
  0.3440403  0.91105871 0.60441339 0.824308  ]
 [0.21979723 0.73287936 0.9504761  0.48371694 0.81366007 0.2497226
  0.50401593 0.09314561 0.08304969 0.34534915]
 [0.80306737 0.87464488 0.95421845 0.38173253 0.40592503 0.33652219
  0.18127357 0.56364526 0.83340889 0.62219076]
 [0.43205207 0.84256677 0.88514561 0.14329422 0.80766662 0.14896355
  0.22797937 0.76089802 0.10329723 0.57424743]]
[[ 0.04472903 -0.13507294 -0.21055793  0.36383705 -0.12000587 -0.03434053
  -0.23348588 -0.10934049  0.08301308  0.35122447]
 [-0.53970636  0.15461998  0.18849744  0.28029901  0.27139249 -0.58151629
  -0.27031136  0.29670704 -0.00993828  0.20995633]
 [-0.22778404  0.28529809  0.50289483  0.03613567  0.36607881 -0.19785866
   0.05643467 -0.35443566 -0.36453158 -0.10223212]
 [ 0.20740448  0.27898199  0.35855556 -0.21393036 

#### 59. How to sort an array by the nth column? (★★☆)

In [42]:
z = numpy.random.randint(0, 10, (3, 3))
print(z)
print(z[z[:, 2].argsort()])

[[4 4 5]
 [9 6 6]
 [6 8 1]]
[[6 8 1]
 [4 4 5]
 [9 6 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [50]:
z = numpy.random.randint(0, 3, (3, 10))
print(z)
print(z.any(axis=0))
print((~z.any(axis=0)))
print((~z.any(axis=0)).any())

[[2 0 1 0 1 2 2 0 2 0]
 [2 2 2 1 0 2 1 0 0 0]
 [1 2 0 2 0 0 2 0 1 2]]
[ True  True  True  True  True  True  True False  True  True]
[False False False False False False False  True False False]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [55]:
z = numpy.random.uniform(0, 1, 10)
print(z)
x = 0.5
print(numpy.abs(z - x))
print(numpy.abs(z - x).argmin())
print(z.flat[numpy.abs(z - x).argmin()])
print(z[numpy.abs(z - x).argmin()])

[0.65656662 0.33146828 0.94084878 0.29925194 0.01326644 0.3416055
 0.28571095 0.76624258 0.02533415 0.14270754]
[0.15656662 0.16853172 0.44084878 0.20074806 0.48673356 0.1583945
 0.21428905 0.26624258 0.47466585 0.35729246]
0
0.6565666210361725
0.6565666210361725


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [58]:
a = numpy.arange(3).reshape(3, 1)
b = numpy.arange(3).reshape(1, 3)
print(a)
print(b)
it = numpy.nditer([a, b, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [60]:
class NamedArray(numpy.ndarray):
    def __new__(cls, array, name='no name'):
        obj = numpy.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize_(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', 'no name')

z = NamedArray(numpy.arange(10), 'range_10')
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)